#!/usr/bin/python

# Import modules for CGI handling 
import cgi, cgitb 
import time

"""
#while 1:
#data = open('1.grass10.jpg', 'rb').read()
#print "Content-Type: image/jpg\nContent-Length: %d\n" % len(data)
#print data

def refresh_display():
	# Create instance of FieldStorage 
	form = cgi.FieldStorage() 

	# Get data from fields
	first_name = form.getvalue('first_name')
	last_name  = form.getvalue('last_name')
	button2 = form.getvalue('button2')

	print #

	data_uri = open('1.grass10.jpg', 'rb').read().encode('base64').replace('\n', '')
	img_tag = '<img src="data:image/jpg;base64,{0}">'.format(data_uri)
	print (img_tag)


	#print "Content-type:text/html\r\n\r\n"
	print "<html>"
	print "<head>"
	print "<title>Hello - Second CGI Program</title>"
	print "</head>"
	print "<body>"
	print "<h2>Hello %s %s</h2>" % (first_name, last_name)

	print '<form name="form2" action="/cgi-bin/script.py" method="get">'
	#print '<input type="text" name="button2" />' % ('button2')
	print '<input type="submit" value="Submit" name="Submit2"/>'
	print '</form>'

	#print '<input type="submit" value="Submit" name="Submit1"/>'
	#print '<input type="submit" value="Submit" name="Submit2"/>'
	print "</body>"
	print "</html>"
	
	if "Submit1" in form:
	    button = 1
	    print "button 1 pressed"
	elif "Submit2" in form2:
	    button = 2
	    print "button 2 pressed"
	else:
	    print "Couldn't determine which button was pressed."
	
	if "button2" in form:
		print "button2 pressed"
	print "hi"
"""
def execute_program():
	#import os
	#os.system("./test_gui1.py")
	#time.sleep(2) 
	#print "Location: http://localhost:8002/"
	print "Location: http://isotope11.com"

if __name__ == '__main__':
	#button = refresh_display()
	execute_program()

    	#main()
